# Generated by Django 4.0.4 on 2022-06-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_date_t_quality_inspection_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quality_inspection',
        ),
    ]
